services:
  # Backend service (FastAPI) - Development mode
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ROOT_URL=http://localhost:8000
      - DATABASE_URL=sqlite:///database.db
      - SECRET_JWT=mysupersecretkey
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-your-google-api-key}
    volumes:
      - ./database.db:/app/database.db
      - ./src:/app/src  # Live reload for development
    networks:
      - soda-network
    command: ["uv", "run", "fastapi", "dev", "src/main.py", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend service (React) - Development mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite dev server port
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Anonymous volume for node_modules
    networks:
      - soda-network
    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "5173"]

networks:
  soda-network:
    driver: bridge
